### ISSUE TITLE
Init wizard installs old version

### ISSUE THREAD

**Issue by elygeo** [eslint/create-config#106]
### Environment

Node version: v21.7.3
npm version: 10.5.2
Local ESLint version: v9.1.1
Operating System: MacOS

### What parser are you using?

Default (Espree)

### What did you do?

$ npm init @eslint/config@latest
(accept defaults)

$ npx eslint --version

### What did you expect to happen?

v9.1.1

### What actually happened?

v8.57.0

**Comment by nzakas** [comment]
@aladdin-add can you take a look at this?

**Comment by aladdin-add** [comment]
it will be "fixed" if we remove the style guides. :) https://github.com/eslint/create-config/issues/101

**Comment by aladdin-add** [comment]
I was able to repro!

However, it's expected behavior: the required deps `eslint-plugin-react` does not allow eslint v9. So, package managers like npm will install eslint v8 instead.
https://github.com/jsx-eslint/eslint-plugin-react/blob/4467db503e38b9356517cf6926d11be544ccf4b1/package.json#L81

while yarn v1 installed eslint v9. 🤔

**Comment by nzakas** [comment]
Should we maybe detect this and then ask if people want to override and force ESLint 9 to be installed?

**Comment by aladdin-add** [comment]
I don't think it's appropriate (at least for most users) - eslint v9 is not supported by the plugin, and not even tested. We can output some information, the advanced users can upgrade to v9 manually if they are willing to try, just like use-at-your-own-risks.

**Comment by aladdin-add** [comment]
some known issues: https://github.com/jsx-eslint/eslint-plugin-react/issues/3699

**Comment by nzakas** [comment]
What part isn't appropriate?

I think telling people that they're using a plugin that isn't supported in v9 and then giving them the option to continue or install v8 makes sense in all cases. Is there something I'm missing?

**Comment by aladdin-add** [comment]
It doesn't seem reasonable to install a version that may not work. good to use `@eslint/backcompat` as described in https://github.com/eslint/eslint/issues/18398.

**Comment by nzakas** [comment]
Sorry, I think maybe I'm not explaining myself well.

What I think we should do for now is, if they select React, to message them saying, "The React plugin works in ESLint < 9.0.0. Would you like to install ESLint 8.57?" (or something like that) To make it obvious what is happening. If they answer "No", then we just don't add the plugin. Does that make sense?

And yes, once the compat utility is published, we can always go back and wrap the plugin and avoid this mess.

**Comment by aladdin-add** [comment]
I see, thanks for explaining. SGTM. 👍

**Comment by nzakas** [comment]
Compat utility is ready: https://eslint.org/blog/2024/05/eslint-compatibility-utilities/
