### ISSUE TITLE
Shouldn't it be the opposite?

### ISSUE THREAD

**Issue by agecode-debug** [eslint/create-config#129]
![image](https://github.com/eslint/create-config/assets/99119244/f011f4ff-e10d-4d71-86f5-b723f03997b5)
like
`this.result.configFilename = isESMModule ? "eslint.config.js" : "eslint.config.mjs";`
should instead be
`this.result.configFilename = isESMModule ? "eslint.config.mjs" : "eslint.config.js";`
No ?

**Comment by aladdin-add** [comment]
it's working as expected - the generated config is always esm, and it has be `.mjs` in `type: "commonjs"`.

Have you encountered any problems? Please provide as much detail as possible.
