### ISSUE TITLE
eslint-config-love

### ISSUE THREAD

**Issue by mightyiam** [eslint/create-config#138]
Following up with #101, eslint-config-love does not offer style rules by now. Does that mean it would be welcomed back as an option in the wizard, possibly?

**Comment by nzakas** [comment]
Looking over your docs, I don't see any reason we'd include this. It's not popular (by download count) and doesn't seem to fill a need that most users would have when setting up ESLint. We're trying to laser-focus on what's offered and this just doesn't meet the bar.

**Comment by mightyiam** [comment]
Hey. Sorry for not explaining this sooner. Regarding the popularity. Just wanna make sure it's not overlooked. eslint-config-love is a rename of eslint-config-standard-with-typescript. Here are some popularity stats ([source](https://github.com/mightyiam/eslint-config-love/network/dependents?package_id=UGFja2FnZS0zNjcxMzc3MQ%3D%3D)):

> 94,562 Repositories, 6,495 Packages

Here is how [the adoption of the renamed package is going](https://npmcharts.com/compare/eslint-config-standard-with-typescript,eslint-config-love?minimal=true).

**Comment by mightyiam** [comment]
@nzakas ping

**Comment by aladdin-add** [comment]
to clarify: it removed all hard-coded style guides  (not only ts).  now it's recommended to use `--config` to apply a 3rd-party config:

```bash
npm init @eslint/config@latest -- --config eslint-config-love
```

**Comment by mightyiam** [comment]
Does style mean formatting?
