### ISSUE TITLE
Add Yarn and pnpm support in eslint --init

### ISSUE THREAD

**Issue by mateushnsoares** [eslint/create-config#20]
---
name: "Add yarn support for --init"
about: Request a change that is not a bug fix, rule change, or new rule
title: 'Add yarn support for --init'
labels: enhancement, triage, core
assignees: ''

---

**The version of ESLint you are using.**

7.8.1

**The problem you want to solve.**

> I'm 👎 on adding this in. Yarn is a popular package manager, but it's not an official one. There're a bunch of other package managers out there. If the user chose to use yarn as an NPM replacement (which is perfectly fine), they should be ready to do some tweaking by hands.

_Originally posted by @ilyavolodin in https://github.com/eslint/eslint/pull/9023#issuecomment-323495264_

The yarn is not official but is more used of NPM. And I don't see a problem on support Yarn ?? I really don't understand why closed  **[THIS PR](https://github.com/eslint/eslint/pull/9023)**

**Your take on the correct solution to problem.**

Add yarn and pnpm support.

**Are you willing to submit a pull request to implement this change?**

No

**Comment by stereokai** [comment]
Gotcha. Keeping my fingers crossed! ;)

**Comment by aladdin-add** [comment]
this is unblocked.

@snitin315 are you still interested in working on this? 😄

**Comment by snitin315** [comment]
@aladdin-add No, not at the moment.

**Comment by harish-sethuraman** [comment]
I'd like to pick this up 😄
