### ISSUE TITLE
Command to create config file doesn't recognize space on Users name

### ISSUE THREAD

**Issue by AnaLinsDev** [eslint/create-config#21]
### Environment

i can't, that's the issue

### What parser are you using?

Other

### What did you do?

command : yarn create @eslint/config

I've tried to create the config file, but it gives me an error 'C:\Users\Ana' is not recognized as an internal or external command, 
the original is 'C:\Users\Ana Júlia Lins/...', i believe that it doesn't recognize spaces on user names.

### What did you expect to happen?

config file created

### What actually happened?

 error 'C:\Users\Ana' is not recognized as an internal or external command

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nzakas** [comment]
Thanks for the report. I’m not sure if this is a problem on the eslint side or the yarn side. @aladdin-add any idea?

**Comment by aladdin-add** [comment]
@AnaLinsDev have you tried `npm init @eslint/config`? It's mostly like an issue in yarn If it does work with npm.

**Comment by AnaLinsDev** [comment]
that's really a yarn issue. thank you.
