### ISSUE TITLE
Being front for access to diversity of plugins and configs

### ISSUE THREAD

**Issue by brettz9** [eslint/create-config#22]
I think it would be excellent to have a front-end which allowed for incorporating a great diversity and plurality of plugins and configs.

Being able to choose anything from https://github.com/dustinspecker/awesome-eslint or the like--a site which may incidentally also help with categorization within `create-config`--would I think allow for better discovery of useful tools from the ecosystem, and also foster the community enforcing better control of their code. I personally find it difficult to live without plugins like unicorn, import, promise, eslint-comments, as well as special environments ones like plugins for node, html, markdown, no-unsanitized, compat, etc., but I think there is a kind of inertia for some projects that they ought to stick mostly just to the default rules for some self-limiting reason. With ESLint itself demonstrating its openness to plugins, and not favoring certain configs over others (beyond sorting them roughly in order by some objective criteria like number of stars on GitHub), I think this approach could be a good one.

I'm not inclined to work on this myself at the moment, but wanted to share it as an idea in case it might interest.

**Comment by nzakas** [comment]
I’m not quite sure what it is you’re proposing. Are you suggesting that we somehow incorporate more options into the `—init` command? Or are you suggesting we build out a website?

**Comment by brettz9** [comment]
More options into `--init`. But yeah, was also thinking it may be interesting for this project to be adapted as a polyglot project, where a site like the demo might indeed allow downloading a config file. Some folks may be more comfortable doing this than working on the command line. But the first idea is more in my thoughts at this time.

**Comment by nzakas** [comment]
Gotcha. Can you describe specifically what you have in mind?

It’s hard to evaluate something as amorphous as “we should help people find plugins”. 😁

**Comment by brettz9** [comment]
Sure... :-)

Was thinking it could be a sizeable wizard app, albeit one which did not have too many choices on screen at a time.

For example, looking at the [awesome-eslint](https://github.com/dustinspecker/awesome-eslint) categories as food for ideas, a page might begin:

***Do you wish to:***
1. [x] get started quickly with just a few questions
2. [x] explore many of the available options in the ESLint plugin ecosystem?

Then if choosing no. 2, be shown:

***Are you interested in plugins to:***

1. [x] Enhance general **Code Quality**?
2. [x] Check for **Compatibility** in coding environments (e.g., browsers or ES versions)
3. [x] **Deprecating** features or Disabling plugins?
4. [x] Targeting JavaScript **embedded** within our languages like HTML?
5. [x] Working in a friendly way with a particular **framework** or **library**
6. [x] Working in a friendly way with other **languages and environments** (e.g., Node, CSS, TypeScript, JSON) 
7. [x] Tweak ESLint in **miscellaneous** ways (e.g., converting rules to errors)
8. [x] Enforce specific **Practices and Specific ES Features** (e.g., checking imports, arrays, comments, promises, functional programming, etc.)
9. [x] Watch for **Performance** issues
10. [x] Check against **Security** concerns
11. [x] Enforces particular **Style** rules (e.g., import sort order, padding between statements)
12. [x] Better work with specific **Testing Tools** (e.g., Mocha, Chai, Jest, Cypress)

if clicking yes to no. 1, would give `eslint-plugin-unicorn`, `eslint-plugin-sonarjs`, etc. as options, for example, as per items in `awesome-eslint`'s Code Quality section, and same with the rest.

I don't have too much of a strong idea of the exact UI except to ensure that things are categorized well to avoid too many items per category and ensure items are grouped as most salient to the average person (as we've hopefully done with awesome-eslint).

Btw, one really exciting tool concept out there is [`mrm`](https://github.com/sapegin/mrm) which seeks to autogenerate files including ESLint configs on a codemods type of approach (also being usable to modify existing files). The project hasn't always been super responsive though, or otherwise, I might have submitted some of these ideas there.

**Comment by nzakas** [comment]
Interesting idea. I do have some concerns, though:

1. I could see this turning into a popularity contest where every plugin author wants to get added and we will end up needing to draw some arbitrary line between who is included and who is not. This isn’t something I’d want to deal with on an ongoing basis.
2. I’m not sure we want the init wizard to be more complicated. Command lines are lousy for doing a lot of configuration. The init wizard was always intended to be a QuickStart, not an all-encompassing configuration tool.
3. We would constantly be fighting plugin compatibility issues. (Compatibility between plugins, with ESLint, etc.)

I think a better solution to the same problem is a website that makes it easy to discover plugins and rules. That’s obviously a massive undertaking but I think a much better experience for all involved.

**Comment by brettz9** [comment]
> Interesting idea. I do have some concerns, though:
> 
>     1. I could see this turning into a popularity contest where every plugin author wants to get added and we will end up needing to draw some arbitrary line between who is included and who is not. This isn’t something I’d want to deal with on an ongoing basis.

Sure, understandable.  I guess we are already taking care of these kinds of choices with `awesome-eslint`, so maybe we in the community could help out. (See below)

>     2. I’m not sure we want the init wizard to be more complicated. Command lines are lousy for doing a lot of configuration. The init wizard was always intended to be a QuickStart, not an all-encompassing configuration tool.

Sure, understandable. I guess this brings me back to mrm since that can be set up with customizable defaults such that projects wouldn't have to go through the hoops of going through a load of screens each time. If they only wanted a choice between their two favorite configs, they could do so. And mrm allows through its interface installing third-party presets on npm so `awesome-eslint` could in theory make its own version with all choices potentially available but which also allowed customization to avoid a bloated series of choices.

Tbh, I think ESLint focusing on developing or forking that project might be time better spent than a limited tool--however understandable I think it is to offer *something* as it does--but I know there is scope creep and all.

>     3. We would constantly be fighting plugin compatibility issues. (Compatibility between plugins, with ESLint, etc.)
> 
> 
> I think a better solution to the same problem is a website that makes it easy to discover plugins and rules. That’s obviously a massive undertaking but I think a much better experience for all involved.

Yeah, I can see that concern on making sure it all works, but I tend to view it from the point of view of a developer who is used to either:

1. Living with a plugin advertising not yet supporting a new version while it effectively does (courtesy of `--legacy-peer-deps`)
2. Finding out by trial and error if I need to downgrade or drop a plugin. The big thing I think is knowing what's available, so I can make the choice, watch the repo for updates, etc.

But again, upon your input and reflection, I do think maybe this is better supported through other tools like mrm.

Still, given the centrality of plugins to some tools' great success (like Firefox back in the day), you might want to give a little thought to that mrm idea because I think that might bring these advantages: 

1. Avoid blessing any particular configurations while still promoting extensibility
2. Have discovery of plugins and configs fostered by the popularizing of a mechanism which the community can expand
3. Offer something more powerful to the community than `create-config` as it currently is, with mrm's support for customizable and extensible code modding against even an already existing ESLint config, etc.)

While a website might appeal to some, I think the developer's developer might prefer all this control, e.g., so, as mentioned, they could, via mrm config, have some decisions automated based on their interests and be presented with only those choices which they vary about.

I'll close the issue, but just something to possibly consider.
