### ISSUE TITLE
Add an option to generate a config for Prettier

### ISSUE THREAD

**Issue by segevfiner** [eslint/create-config#28]
Prettier is quite a popular option for formatting JS/TS projects nowadays. Using it with ESLint requires disabling rules that would otherwise conflict with its auto formatting, using a config preset they provide, and optionally, also using their plugin to have ESLint error on unformatted code.

It would be nice if this config generator add support for generating appropriate recommended config for using Prettier with ESLint.

The Vue CLI and Vite have support for this AFAIK.

**Comment by aladdin-add** [comment]
I had filed an issue to support `--config`, it allows users to input a shared config. so it can be resolved if the shared config has supported prettier?

**Comment by segevfiner** [comment]
I kinda think it just needs an option like you have for other kinds of styles like AirBnB.

**Comment by nzakas** [comment]
I don’t think this is practical. Prettier isn’t simply a config we can include, you would also need to set it up to format your code. That’s outside the scope of what ESLint should be doing. I would rather expect such functionality in Prettier itself.

**Comment by segevfiner** [comment]
I'm only talking about setting the ESLint side of things for prettier, which is basically including https://github.com/prettier/eslint-config-prettier

**Comment by nzakas** [comment]
Yeah, that’s what I don’t think makes sense. It won’t do anything on its own.
