### ISSUE TITLE
Can't create config with React + Typescript + Airbnb

### ISSUE THREAD

**Issue by goerlitz** [eslint/create-config#35]
It used to be possible to configure eslint with React + TypeScript + Airbnb style.

Unfortunately, with https://github.com/eslint/create-config/pull/33 Airbnb and Google style was removed.

The PR states that TypeScript is not officially supported by Airbnb and Google. But there is actually [eslint-config-airbnb-typescript](https://github.com/iamturns/eslint-config-airbnb-typescript) to the rescue.

The current situation leave me clueless how to configure eslint with React + TypeScript + Airbnb correctly.
Should I
1. configure eslint with React + Typescript and then manually install Airbnb style with Typescript support, or
2. configure eslint with React + Airbnb style and then manually add Typescript

In either case, I don't really know how to modify .eslintrc appropriately to incorporate the manually installed packages.

I would highly appreciated if this config combination would be supported.

**Comment by aladdin-add** [comment]
you can follow the intro in the [eslint-config-airbnb-typescript](https://github.com/iamturns/eslint-config-airbnb-typescript).

we have a plan to support `--config`, so you can easily run `npm init @eslint/config --config airbnb-typescript` to do so. related: https://github.com/eslint/create-config/issues/23
