### ISSUE TITLE
Bug: Can't install without prompts

### ISSUE THREAD

**Issue by abitrolly** [eslint/create-config#39]
### Environment

Node version: v16.17.1
npm version: 8.15.0
Local ESLint version: 
Global ESLint version: 
Operating System: Ubuntu 22.04

### What parser are you using?

Default (Espree)

### What did you do?

I am trying to install ESLint with all defaults be running `npm init` with `--yes` option, but it doesn't work.

```bash
$ npm init --yes @eslint/config
? How would you like to use ESLint? … 
  To check syntax only
▸ To check syntax and find problems
  To check syntax, find problems, and enforce code style<!-- Paste your code here -->
```

### What did you expect to happen?

All options are chosen by default.

### What actually happened?

Command hangs waiting for input.

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Hi @abitrolly, thanks for the issue!

This was discussed in https://github.com/eslint/create-config/issues/23 and we decided not to support `--yes` for the reasons described in the linked issue thread.

**Comment by abitrolly** [comment]
@mdjermanovic understood. From #23.

> @aladdin-add's original use case, clarified in https://github.com/eslint/create-config/issues/23#issuecomment-1087163068, was to have a non-interactive setup that could be run in an unsupervised scenario.

So what is the official way to install ESLint non-interactively without `--yes`? The only thing that comes to my mind is to throw in some temporary config. I don't know.

**Comment by mdjermanovic** [comment]
You can install eslint package:

```
npm install eslint --save-dev
```

Then, you should add a config file. A simple config to lint es5 browser scripts can be:

```js
// .eslintrc.js
module.exports = {
    extends: ["eslint:recommended"],
    env: {
        browser: true
    }
};
```

This enables recommended built-in rules and enables browser globals.
