### ISSUE TITLE
eslint --init with TypeScript: not setting parserOptions.project

### ISSUE THREAD

**Issue by vilanz** [eslint/create-config#40]
If `Yes` is selected in the `Does your project use TypeScript?` question, `parserOptions.project` is not set, which leads to this on a `eslint .` run:

```
Oops! Something went wrong! :(

ESLint: 8.25.0

Error: Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
```

Although it's fixed simply by adding `"project": "./tsconfig.json"` in `.eslintrc.*`, this could easily be automated.

**Comment by harish-sethuraman** [comment]
Would you like to provide more repro steps? I tried to initialise an config with `yes` to `Does your project use TypeScript?` and the above mentioned error was not thrown. 

Did you have a custom eslint config before?

**Comment by snitin315** [comment]
No response, hence closing.
