### ISSUE TITLE
`--config standard` does not work as document

### ISSUE THREAD

**Issue by aladdin-add** [eslint/create-config#41]
```bash
➜  dn git:(1.x) npm init @eslint/config --config standard   
? How would you like to use ESLint? … 
  To check syntax only
❯ To check syntax and find problems
  To check syntax, find problems, and enforce code style
```

but `-- --config standard` works fine:
```bash
➜  dn git:(1.x) npm init @eslint/config -- --config standard
Checking peerDependencies of eslint-config-standard@latest
The config that you've selected requires the following dependencies:

eslint-config-standard@latest eslint@^8.0.1 eslint-plugin-import@^2.25.2 eslint-plugin-n@^15.0.0 eslint-plugin-promise@^6.0.0
? Would you like to install them now? › No / Yes
```

**Comment by mdjermanovic** [comment]
I remember trying without the `--` and it worked, but it really doesn't work with newer versions of `npm`.

**Comment by aladdin-add** [comment]
the `--` is no needed if using `npx`.  I wish it can be consistent, but ... lol.

**Comment by mdjermanovic** [comment]
It seems to be different behavior with different versions.

* npm 6
  * `npm init @eslint/config --config standard` works
  * `npm init @eslint/config -- --config standard` doesn't work
* npm 7, 8, 9
  * `npm init @eslint/config --config standard` doesn't work
  * `npm init @eslint/config -- --config standard` works

npm 6 is default in Node.js up to v14? Maybe we could update the docs with `--`, and add a note that the commands are different with npm < 7?

**Comment by mdjermanovic** [comment]
> It seems to be different behavior with different versions.
> 
> * npm 6
>   
>   * `npm init @eslint/config --config standard` works
>   * `npm init @eslint/config -- --config standard` doesn't work
> * npm 7, 8, 9
>   
>   * `npm init @eslint/config --config standard` doesn't work
>   * `npm init @eslint/config -- --config standard` works
> 
> npm 6 is default in Node.js up to (including) v14? Maybe we could update the docs with `--`, and add a note that the commands are different with npm < 7?

**Comment by aladdin-add** [comment]
sounds good, will do!

**Comment by harish-sethuraman** [comment]
Seems like vite does the same thing as well. They have provided two commands https://vitejs.dev/guide/#scaffolding-your-first-vite-project

```
# npm 6.x
npm create vite@latest my-vue-app --template vue

# npm 7+, extra double-dash is needed:
npm create vite@latest my-vue-app -- --template vue
```
