### ISSUE TITLE
eslintrc generate error with typescript checked

### ISSUE THREAD

**Issue by vfan** [eslint/create-config#43]
When i generate a eslint config file with typescript checked, the styleGuides seems not correct

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/1477088/199639319-f1106a7a-d43a-4dc0-87c5-368c65120953.png">

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/1477088/199639368-7f891094-5692-49d6-9e94-7e7ed61f5705.png">

@eslint/create-config version
<img width="778" alt="image" src="https://user-images.githubusercontent.com/1477088/199639483-720cd370-9eb8-4638-8dfe-b95af50d4cd1.png">

node:16.13.0
npm:8.19.2

**Comment by aladdin-add** [comment]
![image](https://user-images.githubusercontent.com/13050025/199640143-8485c465-c6d9-418d-a534-5ba0e170e3ba.png)

I was not able to repro. is it a npm caching issue? can you try `npm cache clean --force`, and retry?

**Comment by vfan** [comment]
Yes, I have tried this.
> ![image](https://user-images.githubusercontent.com/13050025/199640143-8485c465-c6d9-418d-a534-5ba0e170e3ba.png)
> 
> I was not able to repro. is it a npm caching issue? can you try `npm cache clean --force`, and retry?

**Comment by aladdin-add** [comment]
or have you globally-installed an older `@eslint/create-config`? I recall npx will use the global version if installed.:)

you can try `npm uninstall @eslint/create-config -g` to uninstall it first.

**Comment by vfan** [comment]
> or have you globally-installed an older `@eslint/create-config`? I recall npx will use the global version if installed.:)
> 
> you can try `npm uninstall @eslint/create-config -g` to uninstall it first.

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1477088/199642588-e1d00b93-3617-411a-9b72-6f6a97ad5f2b.png">


If i `npm i @eslint/create-config -D`, it will correct......

**Comment by vfan** [comment]
`npm init @eslint/config@latest` correct

`npm init @eslint/config@0.4.1` correct

`npm init @eslint/config@0.3.0` not correct

`npm init @eslint/config` not correct, same as 0.3.0

**Comment by vfan** [comment]
I use `npx --node-options=--inspect @eslint/create-config` to  debug this question ,and found 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/1477088/199645569-01238bc9-e239-4188-899d-ba9725ccb941.png">

The path is not a global path
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/1477088/199645504-32e955f8-6eb8-43d3-b705-63223a43aacf.png">


<img width="596" alt="image" src="https://user-images.githubusercontent.com/1477088/199645491-b054a62d-505f-4e75-a6ef-d87843505c47.png">

The @eslint/create-config  version is 0.1.2, it seems a nodejs problem, not your bug.

**Comment by vfan** [comment]
clear the npx cache , it solved. And it give me a tip which not given before
<img width="486" alt="image" src="https://user-images.githubusercontent.com/1477088/199646137-b0fdc524-a36e-45ab-9d14-7d38c6b2b1d9.png">

If i execute `npm init @eslint/config` again, It will not give a tip and not  install this module ,so it's a npx cache problem..
