### ISSUE TITLE
Run `npm init @eslint/config` in non interactive mode

### ISSUE THREAD

**Issue by fedeiglesias** [eslint/create-config#46]
I want to run `npm init @eslint/config` giving the answers through parameters to avoid CLI prompt.

It is possible to do it? 

Thank you in advance

**Comment by aladdin-add** [comment]
is the `--config` you are looking for?

> If you want to use a specific shareable config that is hosted on npm, you can use the --config option and specify the package name:

```bash
# use `eslint-config-semistandard` shared config
# npm 6.x
npm init @eslint/config --config semistandard

# ⚠️ npm 7+, extra double-dash is needed:
npm init @eslint/config -- --config semistandard

# or (`eslint-config` prefix is optional)
npm init @eslint/config -- --config eslint-config-semistandard
```

**Comment by fedeiglesias** [comment]
Hi @aladdin-add 
I don’t think so, with config param I can define extends in .eslintrc, but I want to give responses for the interactive quiz through params. Is that possible?

**Comment by aladdin-add** [comment]
No, the `--config` is the only non-interactive mode.

**Comment by nzakas** [comment]
We can't do a non-interactive mode because the questions aren't simply yes or no.
