### ISSUE TITLE
Proposal: Add `airbnb-with-typescript` to style guides

### ISSUE THREAD

**Issue by EastSun5566** [eslint/create-config#48]
Hi @aladdin-add, 

I am a big fan of TypeScript & The Airbnb style guide. But currently `create-config` doesn't support this option when choosing TS. I think [eslint-config-airbnb-typescript](https://github.com/iamturns/eslint-config-airbnb-typescript) would be a great fit for this.

What are your thoughts on this? If you agree that it would be a good option, I will implement it. Thank you!

**Comment by aladdin-add** [comment]
As said in the readme, it has been supported via `--config`. you can run `npm init -- --config airbnb-typescript`.
