### ISSUE TITLE
feat: support the new flat config

### ISSUE THREAD

**Issue by aladdin-add** [eslint/create-config#51]
the used configs/parsers/plugins supports:

- [x] eslint-plugin-react
- [ ] eslint-plugin-vue: https://github.com/vuejs/eslint-plugin-vue/issues/1291
- [x] ts-eslint: https://github.com/typescript-eslint/typescript-eslint/issues/7694
- [ ] airbnb
- [ ] standard
- [ ] google
- [ ] xo

the difficulty is the new `--config`: is there an easy way to check if the shared config is flat or eslintrc?

**Comment by aladdin-add** [comment]
assigning to me, to avoid it being auto-closed.

**Comment by nzakas** [comment]
Now would be a good time to make this change. We should automatically create an `eslint.config.js` file, without the option to create eslintrc-format files. We will need to ask if the file should be ESM or CommonJS format to ensure the correct syntax is generated.

@aladdin-add do you want to handle this?

**Comment by aladdin-add** [comment]
sure, i'm willing to.

**Comment by nzakas** [comment]
Thanks!
