### ISSUE TITLE
Bug: npm init @eslint/config with "Standard" style generates incorrect setup

### ISSUE THREAD

**Issue by OnkelTem** [eslint/create-config#71]
### Environment

Node version:  16.17
npm version: 8.15
Local ESLint version: 8.47
Global ESLint version: 
Operating System: Linux Ubuntu 22.04

### What parser are you using?

Default (Espree)

### What did you do?

I'm running the configuration wizard like this:

```
npm init @eslint/config
✔ How would you like to use ESLint? · style
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
✔ Where does your code run? · browser
✔ How would you like to define a style for your project? · guide
✔ Which style guide do you want to follow? · standard-with-typescript
✔ What format do you want your config file to be in? · JavaScript
Checking peerDependencies of eslint-config-standard-with-typescript@latest
Local ESLint installation not found.
The config that you've selected requires the following dependencies:

eslint-config-standard-with-typescript@latest @typescript-eslint/eslint-plugin@^5.52.0 eslint@^8.0.1 eslint-plugin-import@^2.25.2 eslint-plugin-n@^15.0.0 || ^16.0.0  eslint-plugin-promise@^6.0.0 typescript@*
✔ Would you like to install them now? · No / Yes
✔ Which package manager do you want to use? · npm
Installing eslint-config-standard-with-typescript@latest, @typescript-eslint/eslint-plugin@^5.52.0, eslint@^8.0.1, eslint-plugin-import@^2.25.2, eslint-plugin-n@^15.0.0 || ^16.0.0 , eslint-plugin-promise@^6.0.0, typescript@*
```

That results to this configuration file:
```js
module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: ['standard-with-typescript', 'plugin:react/recommended'],
  overrides: [
    {
      env: {
        node: true,
      },
      files: ['.eslintrc.{js,cjs}'],
      parserOptions: {
        sourceType: 'script',
      },
    },
  ],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  plugins: ['react'],
  rules: {},
};
```

As you can see, `@typescript-eslint/parser` was not installed during the setup process. This looks a little suspicious, taking into account, that other typescript-including wizard paths end up with `@typescript-eslint/parser` installed and mentioned in the config.

### What did you expect to happen?

Working linting

### What actually happened?

After it finishes,  running `eslint` results to this error:
```
$ $npx eslint './src/**/*.ts'

Oops! Something went wrong! :(

ESLint: 8.47.0

Error: Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /projects/custom/eslint/tts/src/index.ts
    at getParserServices (/projects/custom/eslint/tts/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:22:15)
    at create (/projects/custom/eslint/tts/node_modules/@typescript-eslint/eslint-plugin/dist/rules/dot-notation.js:85:81)
    at Object.create (/projects/custom/eslint/tts/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:41:20)
    at createRuleListeners (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:870:21)
    at /projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1040:110
    at Array.forEach (<anonymous>)
    at runRules (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:977:34)
    at Linter._verifyWithoutProcessors (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1330:31)
    at Linter._verifyWithConfigArray (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1706:21)
    at Linter.verify (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1412:65)

```

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by mdjermanovic** [comment]
Transferred to the eslint/create-config repo.

**Comment by mdjermanovic** [comment]
> As you can see, `@typescript-eslint/parser` was not installed during the setup process. This looks a little suspicious, taking into account, that other typescript-including wizard paths end up with `@typescript-eslint/parser` installed and mentioned in the config.

`@typescript-eslint/parser` is installed as a [dependency](https://github.com/standard/eslint-config-standard-with-typescript/blob/10b234a9304750313cc1b4f310ef0c76c7e2c609/package.json#L56) of `eslint-config-standard-with-typescript`. `@eslint/config` only asks about installing peer dependencies, because `dependencies` are automatically installed by package managers.

> Also, I find it doubtful to not see the proper `parser` value in the user config.

When you choose a shareable config (a style guide), `@eslint/config` lets that config to specify `parser` as there may be different parsers for different file paths. In this case, `parser` is specified [here](https://github.com/standard/eslint-config-standard-with-typescript/blob/10b234a9304750313cc1b4f310ef0c76c7e2c609/src/index.ts#L49).

**Comment by OnkelTem** [comment]
Thanks @mdjermanovic, I see the reasoning. ESlint configs have always been tough tho :)

**Comment by mdjermanovic** [comment]
> ### What actually happened?
> After it finishes, running `eslint` results to this error:
> 
> ```
> $ $npx eslint './src/**/*.ts'
> 
> Oops! Something went wrong! :(
> 
> ESLint: 8.47.0
> 
> Error: Error while loading rule '@typescript-eslint/dot-notation': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
> Occurred while linting /projects/custom/eslint/tts/src/index.ts
>     at getParserServices (/projects/custom/eslint/tts/node_modules/@typescript-eslint/utils/dist/eslint-utils/getParserServices.js:22:15)
>     at create (/projects/custom/eslint/tts/node_modules/@typescript-eslint/eslint-plugin/dist/rules/dot-notation.js:85:81)
>     at Object.create (/projects/custom/eslint/tts/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:41:20)
>     at createRuleListeners (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:870:21)
>     at /projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1040:110
>     at Array.forEach (<anonymous>)
>     at runRules (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:977:34)
>     at Linter._verifyWithoutProcessors (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1330:31)
>     at Linter._verifyWithConfigArray (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1706:21)
>     at Linter.verify (/projects/custom/eslint/tts/node_modules/eslint/lib/linter/linter.js:1412:65)
> ```

Since `eslint-config-standard-with-typescript` enables type-aware rules, which require specifying `parserOptions.project`, given the advice on https://typescript-eslint.io/linting/typed-linting/, perhaps  `eslint-config-standard-with-typescript` could specify `parserOptions: { project: true }` so that the config can work without requiring an additional setup?

**Comment by OnkelTem** [comment]
@mdjermanovic  https://github.com/eslint/create-config/pull/72

**Comment by mightyiam** [comment]
> perhaps `eslint-config-standard-with-typescript` could specify `parserOptions: { project: true }` so that the config can work without requiring an additional setup?

That's brilliant.

https://github.com/standard/eslint-config-standard-with-typescript/issues/1230

**Comment by mdjermanovic** [comment]
Closing as this issue is going to be fixed in the `eslint-config-standard-with-typescript` package.

In the meantime, you'll need to add [`parserOptions.project`](https://typescript-eslint.io/packages/parser/#project) in your config file manually.
