### ISSUE TITLE
Cannot select option for "Where does your code run? Browser, Node"

### ISSUE THREAD

**Issue by regnaio** [eslint/create-config#74]
```shell
npm init @eslint/config

Need to install the following packages:
@eslint/create-config@0.4.6
Ok to proceed? (y) y
✔ How would you like to use ESLint? · problems
✔ What type of modules does your project use? · esm
✔ Which framework does your project use? · none
✔ Does your project use TypeScript? · No / Yes
? Where does your code run? …  (Press <space> to select, <a> to toggle all, <i> to invert selection)
✔ Browser
✔ Node
```

But, `<space>`, `<a>`, `<i>` don't do anything... Pressing `<enter>` results in:

```shell
✔ Where does your code run? · No items were selected
```

**Comment by aladdin-add** [comment]
you don't need to press `<a>` + `<i>`.  `<a>` is to select all, and `<i>` is to unselect all. so you are getting: No items were selected. :)

**Comment by egorFiNE** [comment]
The checkbox color is barely visible.

**Comment by Rec0iL99** [comment]
> The checkbox color is barely visible.

@egorFiNE I think that could be an issue with your terminal font settings and not an issue with the `create-config` tool.

**Comment by egorFiNE** [comment]
> > The checkbox color is barely visible.
> @egorFiNE I think that could be an issue with your terminal font settings and not an issue with the `create-config` tool.

I'm pretty sure that's exactly the problem. However on a b/w terminal or a terminal with no-so-distinct colors that's going to be even more of a problem, so changing the symbol instead of a color would be beneficial with little to no downside.
