### ISSUE TITLE
Add Style Guide Canonical

### ISSUE THREAD

**Issue by KristjanESPERANTO** [eslint/create-config#75]
I recommend including [Canonical](https://www.npmjs.com/package/eslint-config-canonical) as a style guide and considering removing Google as it is no longer being developed. Here's a good comparison of the style guides: https://github.com/gajus/eslint-config-canonical/blob/main/COMPARISON_TABLE.md#table-of-comparison

| Style Guide | Last publish | Rules |
|---|---|---|
|[Canonical](https://www.npmjs.com/package/eslint-config-canonical)  | 3 days ago | 1020 |
|[Airbnb](https://www.npmjs.com/package/eslint-config-airbnb)  | 2 years ago | 446 |
|[Standard](https://www.npmjs.com/package/standard) | 5 month ago | 160 |
|[Google](https://github.com/google/eslint-config-google) | 4 years ago (GitHub repository has been archived) | 65 |
|[XO](https://www.npmjs.com/package/eslint-config-xo) | a year ago | 204 |

**Comment by nzakas** [comment]
I think in general we'll be removing all style guides as ESLint is [getting out of the formatting business](https://eslint.org/blog/2023/10/deprecating-formatting-rules/).

@eslint/eslint-team thoughts?

**Comment by fasttime** [comment]
All style rules contain both formatting and non-formatting rules, I'm only not sure if we want to keep maintaining a list of external configs.

**Comment by KristjanESPERANTO** [comment]
As a user, I find it very convenient to be able to simply select a style guide at this point. That's why I would find it a loss if this was no longer possible.

**Comment by nzakas** [comment]
@mdjermanovic thoughts on this?

**Comment by KristjanESPERANTO** [comment]
So maybe instead of Canonical [ESLint Stylistic](https://eslint.style/)?

**Comment by nzakas** [comment]
ESLint Stylistic isn't a style guide, it's a plugin, so it doesn't make sense to add here.
