### ISSUE TITLE
eslint-config-standard-with-typescript deprecated, moved to eslint-config-love

### ISSUE THREAD

**Issue by tabcat** [eslint/create-config#95]
Getting a deprecation warning after running `npm init @eslint/config`

![Screenshot from 2024-04-12 00-11-10](https://github.com/eslint/create-config/assets/36933094/2bf3485d-ab9a-422c-a47f-2293be12f227)

The deprecation messages says to use `eslint-config-love` package instead. It looks like the https://github.com/mightyiam/eslint-config-standard-with-typescript repo has been renamed to eslint-config-love and has the same exact purpose. Could not find any other references or reasoning for the deprecation.

---
---

If this is all that needs to be changed, I'd be happy to open a PR.

https://github.com/eslint/create-config/blob/1b0d6dda5357b90686d9ec32cb834f451a049710/lib/config-generator.js#L21

```ts
const tsStyleGuides = [
-    { message: "Standard: https://github.com/standard/eslint-config-standard-with-typescript", name: "standard", value: { packageName: "eslint-config-standard-with-typescript", type: "eslintrc" } },
+    { message: "Standard: https://github.com/mightyiam/eslint-config-love", name: "standard", value: { packageName: "eslint-config-love", type: "eslintrc" } },
     { message: "XO: https://github.com/xojs/eslint-config-xo-typescript", name: "xo", value: { packageName: "eslint-config-xo-typescript", type: "eslintrc" } }
 ];
```

**Comment by Delapouite** [comment]
Thanks. A related question: should there be a possibility to select `None` during this question of the initialization wizard?

**Comment by aladdin-add** [comment]
>  A related question: should there be a possibility to select None during this question of the initialization wizard?

1. the question won't be asked when you select 1/2:
```bash
 A related question: should there be a possibility to select None during this question of the initialization wizard?
? How would you like to use ESLint? … 
  To check syntax only
❯ To check syntax and find problems
  To check syntax, find problems, and enforce code style
```

2. when using the `--config`, it means "just use this shared config, don't ask any questions". you can see it in the readme.

**Comment by aladdin-add** [comment]
The brand `standard` no longer seems applicable; since it's a new brand, I believe we can simply remove it. / @voxpelli

**Comment by voxpelli** [comment]
See https://github.com/standard/standard/issues/1957 and https://github.com/standard/standard/issues/1948
